-- =====================================================================
-- Admin account bootstrap — BODY REMOVED
--
-- This migration created the first admin user. Its body contained the
-- account's password in plaintext, as an argument to crypt(), and this
-- repository is public. The body has been removed so the credential is not
-- served from the default branch.
--
-- Removing it here does NOT undo the exposure: the original commit is in the
-- git history and on GitHub. The only real remediation is rotating the
-- password, which has been done separately.
--
-- The filename is kept because supabase_migrations.schema_migrations records
-- it as applied; renaming or deleting it would make a future `supabase db
-- push` disagree with the live ledger.
--
-- LESSON, recorded so the next person does not repeat it: never bootstrap an
-- account from a migration. A migration is source code — it is committed,
-- pushed, mirrored and cached. Create the user through Supabase Auth
-- (dashboard or admin API), where the password never touches the repository,
-- and let the migration grant the ROLE only:
--
--     insert into public.user_roles (user_id, role)
--     select id, 'admin' from auth.users where email = '<address>'
--     on conflict do nothing;
--
-- That statement is safe to commit. The one that was here was not.
-- =====================================================================

-- Intentionally empty.
SELECT 1;
